final List<Map<String, Object>> allRecipes = [
  {
    'title': 'Lemon Tarts',
    'category': 'Pies & Tarts',
    'time': '2 hours (including chilling)',
    'level': 'intermediate',
    'imageUrl':'assets/images/20d735b7-7e89-4876-8578-74c8b3ed61e3.jpeg',
    'ingredients': [
      '• For Pastry: 1¼ cups all-purpose flour\n ⅓ cup powdered sugar\n ¼ tsp salt\n 6 tbsp cold butter (cubed)\n 1 egg yolk\n 2-3 tbsp ice water\n',
      '• For Lemon Curd: 3 large eggs\n ⅓ cup fresh lemon juice\n 1 tbsp lemon zest\n ⅓ cup granulated sugar\n 3 tbsp butter\n',
    ],
    'steps': [
      '• Mix flour powdered sugar and salt. Cut in cold butter until mixture resembles coarse crumbs.\n',
      '• Add egg yolk and ice water gradually until dough forms. Wrap and chill 30 minutes.\n',
      '• Roll out dough and press into tart pans. Prick with fork and chill 15 minutes.\n',
      '• Blind bake at 375°F for 15 minutes and remove weights. Bake 5 more minutes.\n',
      '• For curd: whisk eggs lemon juice zest and sugar in saucepan. Cook over medium heat stirring constantly until thick.\n',
      '• Remove from heat and whisk in butter. Pour into tart shells and chill 1 hour.\n',
    ],
  },
  {
    'title': 'Garlic Bread',
    'category': 'Breads',
    'time': '20 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Air Fryer Garlic Bread.jpeg',
    'ingredients': [
      '• 1 French baguette\n 4 cloves garlic (minced)\n ½ cup butter (softened)\n 2 tbsp fresh parsley (chopped)\n ¼ cup Parmesan cheese\n salt and pepper to taste\n',
    ],
    'steps': [
      '• Preheat oven to 375°F.\n',
      '• Slice baguette diagonally not cutting all the way through.\n',
      '• Mix butter garlic parsley and Parmesan.\n',
      '• Spread mixture between slices and over top.\n',
      '• Wrap in foil and bake 15 minutes. Unwrap and bake 5 more minutes for crispy top.\n',
    ],
  },
  {
    'title': 'Cinnamon Roll',
    'category': 'Pastries',
    'time': '3 hours (including rising)',
    'level': 'intermediate',
    'imageUrl':'assets/images/Apple Cinnamon rolls.jpeg',
    'ingredients': [
      '• For Dough: 3 cups all-purpose flour\n 1 packet active dry yeast\n 1 cup warm milk\n ⅓ cup granulated sugar\n ⅓ cup butter (melted)\n 1 large egg\n 1 tsp salt\n',
      '• For Filling: ½ cup butter (softened)\n ¾ cup brown sugar\n 2 tbsp cinnamon\n',
      '• For Glaze: 1 cup powdered sugar\n 3-4 tbsp milk\n 1 tsp vanilla\n',
    ],
    'steps': [
      '• Dissolve yeast in warm milk with 1 tbsp sugar. Let foam 5 minutes.\n',
      '• Mix flour, remaining sugar and salt. Add yeast mixture butter and egg.\n',
      '• Knead 8 minutes until smooth. Rise in greased bowl 1 hour.\n',
      '• Roll into rectangle spread with filling ingredients.\n',
      '• Roll up tightly and cut into 12 pieces. Place in greased pan.\n',
      '• Rise 30 minutes. Bake at 350°F for 25-30 minutes.\n',
      '• Cool slightly drizzle with glaze.\n',
    ],
  },
  {
    'title': 'Bagels',
    'category': 'Breads',
    'time': '3 hours',
    'level': 'hard',
    'imageUrl':'assets/images/Bagles bread.jpeg',
    'ingredients': [
      '• 4 cups bread flour\n 2 tsp salt\n 1 tbsp sugar\n 1 packet active dry yeast\n 1¼ cups warm water\n 1 tbsp honey (for boiling water)\n',
    ],
    'steps': [
      '• Mix flour salt and sugar. Dissolve yeast in warm water add to flour mixture.\n',
      '• Knead 10 minutes until smooth and elastic. Rise 1 hour.\n',
      '• Divide into 8 pieces shape into bagels. Rise 15 minutes.\n',
      '• Bring large pot of water with honey to boil. Boil bagels 1 minute each side.\n',
      '• Place on baking sheet bake at 425°F for 20-25 minutes until golden.\n',
    ],
  },
  {
    'title': 'Oatmeal Coconut Cookies',
    'category': 'Cookies',
    'time': '30 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Best Oatmeal Coconut Walnut Cookies.jpeg',
    'ingredients': [
      '• 1 cup rolled oats\n 1 cup all-purpose flour\n ½ cup shredded coconut\n ½ cup brown sugar\n ½ cup butter (softened)\n 1 egg\n 1 tsp vanilla\n ½ tsp baking soda\n ½ tsp salt\n',
    ],
    'steps': [
      '• Preheat oven to 350°F.\n',
      '• Cream butter and brown sugar. Add egg and vanilla.\n',
      '• Mix dry ingredients separately then combine with wet ingredients.\n',
      '• Drop spoonfuls on baking sheet and then bake 12-15 minutes until golden.\n',
    ],
  },
  {
    'title': 'Blue Lagoon',
    'category': 'Beverages',
    'time': '5 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Blue Mojito - Foodiosity.jpeg',
    'ingredients': [
      '• 1 oz vodka\n 1 oz blue curaçao\n 4 oz lemonade\n ice cubes\n lemon slice and cherry for garnish\n',
    ],
    'steps': [
      '• Fill glass with ice.\n',
      '• Add vodka and blue curaçao.\n',
      '• Top with lemonade and stir gently.\n',
      '• Garnish with lemon slice and cherry.\n',
    ],
  },
  {
    'title': 'Cold Coffee',
    'category': 'Beverages',
    'time': '5 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Cafe Style Cold Coffee.jpeg',
    'ingredients': [
      '• 2 cups strong brewed coffee (cooled)\n ½ cup milk\n 2 tbsp sugar\n 1 cup ice\n whipped cream (optional)\n',
    ],
    'steps': [
      '• Brew coffee and let cool completely.\n',
      '• Mix coffee, milk and sugar until sugar dissolves.\n',
      '• Pour over ice in glass.\n',
      '• Top with whipped cream if desired.\n',
    ],
  },
  {
    'title': 'Peanut Butter Cookies',
    'category': 'Cookies',
    'time': '25 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Chewy Peanut Butter Cookies.jpeg',
    'ingredients': [
      '• 1 cup peanut butter\n 1 cup granulated sugar\n 1 large egg\n 1 tsp vanilla extract\n ½ tsp baking soda\n ¼ tsp salt\n',
    ],
    'steps': [
      '• Preheat oven to 350°F.\n',
      '• Mix all ingredients until well combined.\n',
      '• Roll into balls and place on baking sheet.\n',
      '• Press with fork in crisscross pattern.\n',
      '• Bake 10-12 minutes until edges are set.\n',
    ],
  },
  {
    'title': 'Chocolate Chip Cookies',
    'category': 'Cookies',
    'time': '25 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Chocolate Chip Cookies.jpeg',
    'ingredients': [
      '• 2¼ cups all-purpose flour\n 1 tsp baking soda\n 1 tsp salt\n 1 cup butter (softened)\n ¾ cup granulated sugar\n ¾ cup brown sugar\n 2 large eggs\n 2 tsp vanilla\n 2 cups chocolate chips\n',
    ],
    'steps': [
      '• Preheat oven to 375°F.\n',
      '• Mix flour, baking soda and salt.\n',
      '• Cream butter and sugars. Add eggs and vanilla.\n',
      '• Gradually mix in flour mixture then chocolate chips.\n',
      '• Drop spoonfuls on baking sheet. Bake 9-11 minutes.\n',
    ],
  },
  {
    'title': 'Chocolate Tarts',
    'category': 'Pies & Tarts',
    'time': '2 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Chocolate Rice Cakes.jpeg',
    'ingredients': [
      '• For Pastry: 1¼ cups all-purpose flour\n ¼ cup cocoa powder\n ⅓ cup powdered sugar\n ¼ tsp salt\n 6 tbsp cold butter\n 1 egg yolk\n 2-3 tbsp ice water\n',
      '• For Filling: 8 oz dark chocolate (chopped)\n 1 cup heavy cream\n 2 tbsp butter\n',
    ],
    'steps': [
      '• Make pastry as in lemon tarts adding cocoa powder with flour.\n',
      '• Blind bake tart shells at 375°F for 15 minutes.\n',
      '• Heat cream pour over chocolate let sit 2 minutes then stir until smooth.\n',
      '• Whisk in butter pour into tart shells.\n',
      '• Chill 1 hour until set.\n',
    ],
  },
  {
    'title': 'Apple Pie',
    'category': 'Pies & Tarts',
    'time': '2.5 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Classic Apple Pie_ An Amazing Ultimate Recipe for Everyone.jpeg',
    'ingredients': [
      '• For Crust: 2½ cups all-purpose flour\n 1 tsp salt\n 1 cup cold butter (cubed)\n 6-8 tbsp ice water\n',
      '• For Filling: 6 large apples (peeled and sliced)\n ¾ cup sugar\n 2 tbsp flour\n 1 tsp cinnamon\n ¼ tsp nutmeg\n 2 tbsp butter\n',
    ],
    'steps': [
      '• Make pastry and divide in half. Chill 30 minutes.\n',
      '• Roll out bottom crust and place in pie pan.\n',
      '• Mix apples with sugar, flour and spices. Fill crust.\n',
      '• Dot with butter and cover with top crust.\n',
      '• Seal edges and cut vents. Bake at 425°F for 15 minutes then 350°F for 35-40 minutes.\n',
    ],
  },
  {
    'title': 'Black Forest Cake',
    'category': 'Cakes',
    'time': '3 hours',
    'level': 'hard',
    'imageUrl':'assets/images/Classic Black Forest Cake.jpeg',
    'ingredients': [
      '• For Cake: 1¾ cups all-purpose flour\n ¾ cup cocoa powder\n 2 cups sugar\n 2 eggs\n 1 cup buttermilk\n 1 cup strong coffee\n ½ cup vegetable oil\n 1 tsp vanilla\n 2 tsp baking soda\n 1 tsp salt\n',
      '• For Assembly: 2 cups heavy cream\n ¼ cup powdered sugar\n 1 jar cherries in syrup\n 3 tbsp kirsch (optional)\n dark chocolate shavings\n',
    ],
    'steps': [
      '• Mix dry ingredients. Combine wet ingredients separately.\n',
      '• Combine wet and dry ingredients and then bake in 2 pans at 350°F for 30-35 minutes.\n',
      '• Cool completely. Whip cream with powdered sugar.\n',
      '• Slice each cake in half horizontally.\n',
      '• Layer with whipped cream, cherries and kirsch.\n',
      '• Frost outside with cream and decorate with chocolate shavings.\n',
    ],
  },
  {
    'title': 'Lemon Mojito',
    'category': 'Beverages',
    'time': '5 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Country Mojito.jpeg',
    'ingredients': [
      '• 10 fresh mint leaves\n 1 lemon (juiced)\n 2 tbsp sugar\n 2 oz white rum\n club soda\n ice\n lemon slice for garnish\n',
    ],
    'steps': [
      '• Muddle mint leaves with lemon juice and sugar.\n',
      '• Add rum and mix well.\n',
      '• Fill glass with ice and pour mixture over.\n',
      '• Top with club soda and stir gently.\n',
      '• Garnish with lemon slice and mint sprig.\n',
    ],
  },
  {
    'title': 'Pumpkin Pie',
    'category': 'Pies & Tarts',
    'time': '2 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Easy Thanksgiving Pumpkin Pie.jpeg',
    'ingredients': [
      '• For Crust: 1¼ cups all-purpose flour\n ½ tsp salt\n ⅓ cup cold butter\n 3-4 tbsp ice water\n',
      '• For Filling: 1 can (15 oz) pumpkin puree\n 1 can (14 oz) sweetened condensed milk\n 2 large eggs\n 1 tsp cinnamon\n ½ tsp nutmeg\n ½ tsp ginger\n ¼ tsp cloves\n ½ tsp salt\n',
    ],
    'steps': [
      '• Make pastry , roll out and place in pie pan.\n',
      '• Mix all filling ingredients until smooth.\n',
      '• Pour into crust and bake at 425°F for 15 minutes.\n',
      '• Reduce to 350°F. Bake 35-40 minutes until knife inserted comes out clean.\n',
    ],
  },
  {
    'title': 'Garlic Naan',
    'category': 'Breads',
    'time': '2 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Garlic Naan with Garlic Browned Butter.jpeg',
    'ingredients': [
      '• 2 cups all-purpose flour\n 1 tsp active dry yeast\n 1 tsp sugar\n ½ tsp salt\n ¾ cup warm water\n 2 tbsp yogurt\n 2 tbsp vegetable oil\n 4 cloves garlic (minced)\n 3 tbsp butter (melted)\n 2 tbsp fresh cilantro\n',
    ],
    'steps': [
      '• Mix yeast, sugar and warm water. Let foam 5 minutes.\n',
      '• Mix flour and salt, add yeast mixture, yogurt and oil.\n',
      '• Knead 8 minutes and let it rise 1 hour.\n',
      '• Divide into 8 pieces then roll thin.\n',
      '• Cook on hot skillet 2-3 minutes per side.\n',
      '• Brush with garlic butter mixture and cilantro.\n',
    ],
  },
  {
    'title': 'Honey Buns',
    'category': 'Pastries',
    'time': '3 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Homemade Honey Buns.jpeg',
    'ingredients': [
      '• For Dough: 3 cups all-purpose flour\n 1 packet active dry yeast\n ¼ cup sugar\n 1 tsp salt\n ½ cup warm milk\n ¼ cup butter (melted)\n 1 egg\n',
      '• For Filling: ¼ cup butter (softened)\n ½ cup brown sugar\n 1 tsp cinnamon\n',
      '• For Glaze: 1 cup powdered sugar\n 3 tbsp honey\n 2-3 tbsp milk\n',
    ],
    'steps': [
      '• Dissolve yeast in warm milk with 1 tbsp sugar.\n',
      '• Mix flour, remaining sugar and salt. Add yeast mixture, butter and egg.\n',
      '• Knead 8 minutes and let it rise 1 hour.\n',
      '• Roll out and spread with filling then roll up and slice.\n',
      '• Rise 30 minutes and bake at 350°F for 20-25 minutes.\n',
      '• Drizzle with honey glaze while warm.\n',
    ],
  },
  {
    'title': 'Pineapple Cake',
    'category': 'Cakes',
    'time': '1.5 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/How to Make the Best Pineapple Coconut.jpeg',
    'ingredients': [
      '• 1½ cups all-purpose flour\n 1 cup sugar\n ½ cup butter (softened)\n 2 eggs\n 1 tsp baking powder\n ½ tsp salt\n ½ cup pineapple juice\n 1 cup crushed pineapple (drained)\n 1 tsp vanilla\n',
    ],
    'steps': [
      '• Preheat oven to 350°F.\n',
      '• Cream butter and sugar. Add eggs one at a time.\n',
      '• Mix dry ingredients separately.\n',
      '• Alternate adding dry ingredients and pineapple juice.\n',
      '• Fold in crushed pineapple and vanilla.\n',
      '• Bake in greased pan 30-35 minutes.\n',
    ],
  },
  {
    'title': 'Chocolate Cupcakes',
    'category': 'Cupcakes',
    'time': '45 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Incredible Chocolate Cupcakes with Chocolate Fudge Frosting.jpeg',
    'ingredients': [
      '• 1¾ cups all-purpose flour\n ¾ cup cocoa powder\n 2 cups sugar\n 2 tsp baking soda\n 1 tsp baking powder\n 1 tsp salt\n 2 eggs\n 1 cup buttermilk\n 1 cup strong coffee\n ½ cup vegetable oil\n 1 tsp vanilla\n',
    ],
    'steps': [
      '• Preheat oven to 350°F.\n',
      '• Mix all dry ingredients.\n',
      '• Combine wet ingredients separately.\n',
      '• Mix wet and dry ingredients until just combined.\n',
      '• Fill cupcake liners ⅔ full and bake 18-20 minutes.\n',
    ],
  },
  {
    'title': 'Croissants',
    'category': 'Pastries',
    'time': '8 hours (including overnight chilling)',
    'level': 'hard',
    'imageUrl':'assets/images/Italian croissants.jpeg',
    'ingredients': [
      '• 3 cups bread flour\n 1 tbsp sugar\n 1 tsp salt\n 1 packet active dry yeast\n 1 cup warm milk\n 1 cup cold butter\n',
    ],
    'steps': [
      '• Mix flour, sugar,salt and yeast. Add warm milk\n knead 5 minutes.\n',
      '• Rise 1 hour, punch down and chill overnight.\n',
      '• Roll dough into rectangle and place butter in center.\n',
      '• Fold dough over butter, roll out and fold in thirds.\n',
      '• Repeat folding process 2 more times and chilling 30 minutes between.\n',
      '• Roll out, cut into triangles and roll up from wide end.\n',
      '• Rise 2 hours and bake at 400°F for 15-20 minutes.\n',
    ],
  },
  {
    'title': 'Mocha Cupcakes',
    'category': 'Cupcakes',
    'time': '45 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Mocha cupcake_.jpeg',
    'ingredients': [
      '• 1¾ cups all-purpose flour\n ¾ cup cocoa powder\n 2 cups sugar\n 2 tsp baking soda\n 1 tsp baking powder\n 1 tsp salt\n 2 eggs\n 1 cup buttermilk\n 1 cup strong coffee\n ½ cup vegetable oil\n 1 tsp vanilla\n 2 tbsp instant coffee powder\n',
    ],
    'steps': [
      '• Follow chocolate cupcake recipe after adding instant coffee powder to dry ingredients.\n',
      '• Bake at 350°F for 18-20 minutes.\n',
      '• Top with coffee buttercream frosting.\n',
    ],
  },
  {
    'title': 'Cream Puffs',
    'category': 'Pastries',
    'time': '1 hour',
    'level': 'intermediate',
    'imageUrl':'assets/images/Mom’s Famous Cream Puffs.jpeg',
    'ingredients': [
      '• For Choux Pastry: 1 cup water\n ½ cup butter\n 1 cup all-purpose flour\n 4 large eggs\n ¼ tsp salt\n',
      '• For Filling: 2 cups heavy cream\n ¼ cup powdered sugar\n 1 tsp vanilla\n',
    ],
    'steps': [
      '• Bring water and butter to boil. Add flour all at once and stir until smooth.\n',
      '• Cool slightly, add eggs one at a time and beat well.\n',
      '• Pipe onto baking sheet and bake at 425°F for 15 minutes then 350°F for 20 minutes.\n',
      '• Cool completely then whip cream with sugar and vanilla.\n',
      '• Cut tops off puffs and fill with cream.\n',
    ],
  },
  {
    'title': 'Multigrain Bread',
    'category': 'Breads',
    'time': '4 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Multigrain Bread Recipe.jpeg',
    'ingredients': [
      '• 2 cups bread flour\n 1 cup whole wheat flour\n ½ cup rolled oats\n ¼ cup sunflower seeds\n ¼ cup flaxseeds\n 2 tsp salt\n 1 tbsp honey\n 1 packet active dry yeast\n 1¼ cups warm water\n 2 tbsp olive oil\n',
    ],
    'steps': [
      '• Mix flours, oats, seeds and salt.\n',
      '• Dissolve yeast in warm water with honey.\n',
      '• Add yeast mixture and oil to flour mixture.\n',
      '• Knead 10 minutes and rise 1.5 hours.\n',
      '• Shape into loaf and rise 1 hour.\n',
      '• Bake at 375°F for 35-40 minutes.\n',
    ],
  },
  {
    'title': 'Biscoff Cheesecake',
    'category': 'Cakes',
    'time': '6 hours (including chilling)',
    'level': 'intermediate',
    'imageUrl':'assets/images/No Bake Biscoff Cheesecake.jpeg',
    'ingredients': [
      '• For Crust: 2 cups Biscoff cookies (crushed)\n 5 tbsp butter (melted)\n',
      '• For Filling: 24 oz cream cheese (softened)\n ¾ cup sugar\n 3 large eggs\n ½ cup Biscoff spread\n 1 tsp vanilla\n ¼ cup heavy cream\n',
    ],
    'steps': [
      '• Mix crushed cookies with melted butter then press into springform pan.\n',
      '• Beat cream cheese and sugar until smooth.\n',
      '• Add eggs one at a time then Biscoff spread, vanilla and cream.\n',
      '• Pour over crust and bake at 325°F for 55-60 minutes.\n',
      '• Cool completely then chill 4 hours.\n',
    ],
  },
  {
    'title': 'Nutella Stuffed Cookies',
    'category': 'Cookies',
    'time': '30 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Nutella Stuffed Cookies.jpeg',
    'ingredients': [
      '• 2¼ cups all-purpose flour\n 1 tsp baking soda\n 1 tsp salt\n 1 cup butter (softened)\n ¾ cup granulated sugar\n ¾ cup brown sugar\n 2 large eggs\n 2 tsp vanilla\n ½ cup Nutella\n',
    ],
    'steps': [
      '• Mix flour, baking soda and salt.\n',
      '• Cream butter and sugars. Add eggs and vanilla.\n',
      '• Mix in flour mixture.\n',
      '• Scoop dough, add teaspoon of Nutella in center and cover with more dough.\n',
      '• Bake at 375°F for 9-11 minutes.\n',
    ],
  },
  {
    'title': 'Peach Iced Tea',
    'category': 'Beverages',
    'time': '15 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Refreshing Southern Peach Sweet Tea.jpeg',
    'ingredients': [
      '• 6 cups water\n 6 tea bags\n ½ cup sugar\n 2 ripe peaches (sliced)\n 2 tbsp lemon juice\n ice cubes\n fresh mint for garnish\n',
    ],
    'steps': [
      '• Boil 3 cups water and steep tea bags 5 minutes.\n',
      '• Remove bags, add sugar and stir until dissolved.\n',
      '• Add remaining cold water, peach slices and lemon juice.\n',
      '• Chill 2 hours and serve over ice with mint.\n',
    ],
  },
  {
    'title': 'Salted Caramel Cupcakes',
    'category': 'Cupcakes',
    'time': '1 hour',
    'level': 'intermediate',
    'imageUrl':'assets/images/Salted caramel cupcakes.jpeg',
    'ingredients': [
      '• For Cupcakes: 1½ cups all-purpose flour\n 1 cup sugar\n ½ cup butter (softened)\n 2 eggs\n 1 tsp baking powder\n ½ tsp salt\n ½ cup milk\n 1 tsp vanilla\n',
      '• For Caramel: 1 cup sugar\n 6 tbsp butter\n ½ cup heavy cream\n 1 tsp sea salt\n',
    ],
    'steps': [
      '• Make cupcakes: cream butter, sugar, eggs, alternate flour mixture and milk.\n',
      '• Bake at 350°F for 18-20 minutes.\n',
      '• For caramel: heat sugar until melted and golden then add butter and then cream slowly.\n',
      '• Stir in salt and cool slightly.\n',
      '• Fill cupcakes with caramel and top with caramel buttercream.\n',
    ],
  },
  {
    'title': 'Marble Cake',
    'category': 'Cakes',
    'time': '1.5 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Simple Marble Cake Recipe (Moist).jpeg',
    'ingredients': [
      '• 2¾ cups all-purpose flour\n 1 tbsp baking powder\n ½ tsp salt\n 1¾ cups sugar\n ¾ cup butter (softened)\n 4 large eggs\n 2 tsp vanilla\n 1¼ cups milk\n ¼ cup cocoa powder\n 3 tbsp hot water\n',
    ],
    'steps': [
      '• Mix flour, baking powder and salt.\n',
      '• Cream butter and sugar. Add eggs and vanilla.\n',
      '• Alternate adding flour mixture and milk.\n',
      '• Mix cocoa with hot water and combine with ⅓ of batter.\n',
      '• Alternate spoonfuls of vanilla and chocolate batter in pan.\n',
      '• Swirl with knife and bake at 350°F for 55-60 minutes.\n',
    ],
  },
  {
    'title': 'Strawberry Cupcakes',
    'category': 'Cupcakes',
    'time': '45 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Strawberry Cupcakes cup.jpeg',
    'ingredients': [
      '• 1½ cups all-purpose flour\n 1 cup sugar\n ½ cup butter (softened)\n 2 eggs\n 1 tsp baking powder\n ½ tsp salt\n ½ cup milk\n 1 tsp vanilla\n ½ cup fresh strawberries (diced)\n 3 tbsp strawberry jam\n',
    ],
    'steps': [
      '• Cream butter and sugar. Add eggs, vanilla and jam.\n',
      '• Mix dry ingredients separately.\n',
      '• Alternate adding dry ingredients and milk.\n',
      '• Fold in diced strawberries.\n',
      '• Bake at 350°F for 18-20 minutes.\n',
    ],
  },
  {
    'title': 'Vanilla Cupcakes',
    'category': 'Cupcakes',
    'time': '45 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Vanilla Cupcakes.jpeg',
    'ingredients': [
      '• 1½ cups all-purpose flour\n 1 cup sugar\n ½ cup butter (softened)\n 2 eggs\n 1 tsp baking powder\n ½ tsp salt\n ½ cup milk\n 2 tsp vanilla extract\n',
    ],
    'steps': [
      '• Preheat oven to 350°F.\n',
      '• Cream butter and sugar until fluffy.\n',
      '• Add eggs one at a time and then vanilla.\n',
      '• Mix dry ingredients separately.\n',
      '• Alternate adding dry ingredients and milk.\n',
      '• Fill cupcake liners ⅔ full and bake 18-20 minutes.\n',
    ],
  },
  {
    'title': 'Chocolate Cake',
    'category': 'Cake',
    'time': '1.5 hours',
    'level': 'intermediate',
    'imageUrl':'assets/images/Vegan No Bake Chocolate Cheesecake.jpeg',
    'ingredients': [
      '• 1¾ cups all-purpose flour\n ¾ cup cocoa powder\n 2 cups sugar\n 2 tsp baking soda\n 1 tsp baking powder\n 1 tsp salt\n 2 eggs\n 1 cup buttermilk\n 1 cup strong coffee\n ½ cup vegetable oil\n 1 tsp vanilla\n',
    ],
    'steps': [
      '• Mix all dry ingredients in large bowl.\n',
      '• Combine wet ingredients separately.\n',
      '• Add wet to dry ingredients and mix until smooth.\n',
      '• Pour into greased pans and bake at 350°F for 30-35 minutes.\n',
      '• Cool completely before frosting.\n',
    ],
  },
  {
    'title': 'Watermelon Mint Lemonade',
    'category': 'Beverages',
    'time': '15 minutes',
    'level': 'easy',
    'imageUrl':'assets/images/Watermelon Mint Lemonade.jpeg',
    'ingredients': [
      '• 4 cups cubed watermelon\n ½ cup fresh lemon juice\n ¼ cup sugar\n 2 cups cold water\n 15 fresh mint leaves\n ice cubes\n mint sprigs for garnish\n',
    ],
    'steps': [
      '• Blend watermelon until smooth, strain if desired.\n',
      '• Mix lemon juice and sugar until dissolved.\n',
      '• Combine watermelon juice, lemon mixture and water.\n',
      '• Muddle mint leaves gently and add to lemonade.\n',
      '• Serve over ice and garnish with mint sprigs.\n',
    ],
  },
];